import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Aaa'
    Scheduler_SuccessInterval = 0
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '05:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_PackageName = 'auto'  # auto, com.asharmdolls.bilibili
    Emulator_ServerName = 'disabled'  # disabled
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy
    Emulator_ControlMethod = 'minitouch'  # ADB, uiautomator2, minitouch, Hermit, MaaTouch
    Emulator_ScreenshotDedithering = False
    Emulator_AdbRestart = False

    # Group `Error`
    Error_HandleError = True
    Error_SaveError = True
    Error_OnePushConfig = 'provider: null'
    Error_ScreenshotLength = 1

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_TaskHoardingDuration = 0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game

    # Group `AaaTrainingDaily`
    AaaTrainingDaily_BattleExercises = 6  # 0, 1, 2, 3, 4, 5, 6
    AaaTrainingDaily_HuntingLand = 6  # 0, 1, 2, 3, 4, 5, 6
    AaaTrainingDaily_HuntingAir = 6  # 0, 1, 2, 3, 4, 5, 6
    AaaTrainingDaily_HuntingLandAndAir = 6  # 0, 1, 2, 3, 4, 5, 6
    AaaTrainingDaily_ExpansionTraining = 6  # 0, 1, 2, 3, 4, 5, 6
    AaaTrainingDaily_Resourcepreparation = 6  # 0, 1, 2, 3, 4, 5, 6

    # Group `AaaBar`
    AaaBar_SendGifts = True
    AaaBar_Touch = True

    # Group `AaaExploration`
    AaaExploration_Enable = True
    AaaExploration_value = 1
    AaaExploration_option = [1, 2, 3, 4, 5, 6]

    # Group `AaaStorage`
    AaaStorage_Enable = True

    # Group `AaaAirship`
    AaaAirship_Enable = True

    # Group `AaaMainDaily`
    AaaMainDaily_Enable = True

    # Group `AaaTrain`
    AaaTrain_Enable = True

    # Group `AaaFactory`
    AaaFactory_Enable = True

    # Group `AaaRecovery`
    AaaRecovery_Enable = True

    # Group `AaaReward`
    AaaReward_Enable = True

    # Group `Storage`
    Storage_Storage = {}
