from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ACTING_BATTLE_CHECK = Button(area={'cn': (1183, 656, 1191, 658)}, color={'cn': (244, 244, 233)}, button={'cn': (1183, 656, 1191, 658)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/ACTING_BATTLE_CHECK.png'})
ACTING_COMBAT = Button(area={'cn': (936, 547, 957, 568)}, color={'cn': (36, 36, 36)}, button={'cn': (936, 547, 957, 568)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/ACTING_COMBAT.png'})
ACTING_COMBAT_LOCKED = Button(area={'cn': (940, 546, 949, 568)}, color={'cn': (116, 117, 116)}, button={'cn': (940, 546, 949, 568)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/ACTING_COMBAT_LOCKED.png'})
ACTING_COMBAT_READY = Button(area={'cn': (936, 547, 957, 568)}, color={'cn': (28, 132, 136)}, button={'cn': (936, 547, 957, 568)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/ACTING_COMBAT_READY.png'})
BATTLE_STATUS_A = Button(area={'cn': (1122, 372, 1162, 382)}, color={'cn': (152, 141, 65)}, button={'cn': (1109, 404, 1253, 461)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/BATTLE_STATUS_A.png'})
BATTLE_STATUS_B = Button(area={'cn': (1117, 251, 1152, 256)}, color={'cn': (251, 251, 251)}, button={'cn': (1109, 404, 1253, 461)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/BATTLE_STATUS_B.png'})
BATTLE_STATUS_S = Button(area={'cn': (1117, 251, 1152, 256)}, color={'cn': (248, 241, 171)}, button={'cn': (1109, 404, 1253, 461)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/BATTLE_STATUS_S.png'})
COMBAT_PREPARE = Button(area={'cn': (954, 637, 1009, 666)}, color={'cn': (176, 113, 99)}, button={'cn': (908, 619, 1096, 681)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/COMBAT_PREPARE.png'})
COMBAT_PREPARE_LOCKED = Button(area={'cn': (954, 637, 1009, 666)}, color={'cn': (152, 152, 152)}, button={'cn': (954, 637, 1009, 666)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/COMBAT_PREPARE_LOCKED.png'})
COMBAT_SUPPLY = Button(area={'cn': (266, 625, 301, 659)}, color={'cn': (102, 102, 102)}, button={'cn': (266, 625, 301, 659)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/COMBAT_SUPPLY.png'})
COMBAT_SWITCH_ROLE = Button(area={'cn': (373, 624, 408, 658)}, color={'cn': (113, 113, 113)}, button={'cn': (373, 624, 408, 658)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/COMBAT_SWITCH_ROLE.png'})
GET_ITEM = Button(area={'cn': (701, 171, 714, 183)}, color={'cn': (206, 148, 2)}, button={'cn': (701, 171, 714, 183)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/combat/GET_ITEM.png'})
