from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DAILY_SCROLL_AREA = Button(area={'cn': (1141, 88, 1145, 614)}, color={'cn': (70, 70, 70)}, button={'cn': (1141, 88, 1145, 614)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/daily/DAILY_SCROLL_AREA.png'})
OCR_ALLOY = Button(area={'cn': (966, 21, 1070, 47)}, color={'cn': (53, 53, 53)}, button={'cn': (966, 21, 1070, 47)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/daily/OCR_ALLOY.png'})
