from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DAILY_ENTER_CHECK = Button(area={'cn': (326, 186, 404, 200)}, color={'cn': (32, 106, 109)}, button={'cn': (326, 186, 404, 200)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/daily/DAILY_ENTER_CHECK.png'})
OCR_ALLOY = Button(area={'cn': (966, 21, 1070, 47)}, color={'cn': (53, 53, 53)}, button={'cn': (966, 21, 1070, 47)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/daily/OCR_ALLOY.png'})
