from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

MISSION_ALL_FINISH = Button(area={'cn': (1049, 103, 1071, 124)}, color={'cn': (116, 80, 1)}, button={'cn': (1047, 93, 1162, 132)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/reward/MISSION_ALL_FINISH.png'})
MISSION_ALL_NOT_SELECT = Button(area={'cn': (236, 156, 248, 169)}, color={'cn': (33, 33, 33)}, button={'cn': (236, 156, 248, 169)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/reward/MISSION_ALL_NOT_SELECT.png'})
MISSION_ALL_RECEIVED = Button(area={'cn': (1050, 103, 1072, 124)}, color={'cn': (61, 61, 61)}, button={'cn': (1050, 103, 1072, 124)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/reward/MISSION_ALL_RECEIVED.png'})
MISSION_ALL_SELECT = Button(area={'cn': (254, 164, 269, 171)}, color={'cn': (104, 76, 35)}, button={'cn': (61, 148, 259, 218)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/reward/MISSION_ALL_SELECT.png'})
MISSION_CLICK_SAFE_AREA = Button(area={'cn': (302, 571, 727, 696)}, color={'cn': (13, 12, 11)}, button={'cn': (302, 571, 727, 696)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/reward/MISSION_CLICK_SAFE_AREA.png'})
