from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ITEM_GET = Button(area={'cn': (541, 161, 690, 202)}, color={'cn': (114, 121, 125)}, button={'cn': (541, 161, 690, 202)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/ITEM_GET.png'})
LOGIN_ANNOUNCE = Button(area={'cn': (194, 107, 301, 136)}, color={'cn': (6, 167, 169)}, button={'cn': (194, 107, 301, 136)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_ANNOUNCE.png'})
LOGIN_ANNOUNCE_BUTTON = Button(area={'cn': (340, 111, 360, 131)}, color={'cn': (103, 26, 26)}, button={'cn': (340, 111, 360, 131)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_ANNOUNCE_BUTTON.png'})
LOGIN_CHECK = Button(area={'cn': (30, 600, 93, 665)}, color={'cn': (203, 215, 230)}, button={'cn': (30, 600, 93, 665)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_CHECK.png'})
LOGIN_ITEM_MESSAGE_CHECK = Button(area={'cn': (359, 124, 479, 158)}, color={'cn': (130, 131, 133)}, button={'cn': (359, 124, 479, 158)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_ITEM_MESSAGE_CHECK.png'})
LOGIN_SAFE_AREA = Button(area={'cn': (338, 649, 532, 708)}, color={'cn': (50, 46, 34)}, button={'cn': (338, 649, 532, 708)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_SAFE_AREA.png'})
LOGIN_TERMS = Button(area={'cn': (669, 486, 748, 528)}, color={'cn': (47, 177, 230)}, button={'cn': (669, 486, 748, 528)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_TERMS.png'})
LOGIN_UPDATE = Button(area={'cn': (696, 457, 882, 520)}, color={'cn': (204, 65, 41)}, button={'cn': (696, 457, 882, 520)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/handler/LOGIN_UPDATE.png'})
