from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BAR_ARMS_FILTER = Button(area={'cn': (544, 35, 570, 54)}, color={'cn': (77, 60, 14)}, button={'cn': (544, 35, 570, 54)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_ARMS_FILTER.png'})
BAR_CHECK = Button(area={'cn': (1180, 600, 1241, 657)}, color={'cn': (87, 77, 52)}, button={'cn': (1180, 600, 1241, 657)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_CHECK.png'})
BAR_CHECK_2 = Button(area={'cn': (1064, 599, 1125, 656)}, color={'cn': (109, 82, 61)}, button={'cn': (1064, 599, 1125, 656)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_CHECK_2.png'})
BAR_FILTER_CLICK_SAFE_AREA = Button(area={'cn': (183, 24, 514, 139)}, color={'cn': (53, 55, 55)}, button={'cn': (183, 24, 514, 139)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_FILTER_CLICK_SAFE_AREA.png'})
BAR_GIFTS_GIVE = Button(area={'cn': (1103, 487, 1154, 513)}, color={'cn': (176, 125, 146)}, button={'cn': (1088, 440, 1166, 520)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_GIFTS_GIVE.png'})
BAR_GIFTS_GIVE_CHECK = Button(area={'cn': (558, 309, 657, 334)}, color={'cn': (134, 132, 131)}, button={'cn': (558, 309, 657, 334)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_GIFTS_GIVE_CHECK.png'})
BAR_GIFTS_GRID_CHECK = Button(area={'cn': (1178, 222, 1190, 258)}, color={'cn': (112, 116, 116)}, button={'cn': (1178, 222, 1190, 258)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_GIFTS_GRID_CHECK.png'})
BAR_MENU = Button(area={'cn': (333, 225, 367, 257)}, color={'cn': (211, 56, 144)}, button={'cn': (269, 156, 814, 296)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_MENU.png'})
BAR_SWITCH_LEFT = Button(area={'cn': (18, 289, 58, 351)}, color={'cn': (111, 109, 99)}, button={'cn': (18, 289, 58, 351)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_SWITCH_LEFT.png'})
OCR_BAR_AFFINITY = Button(area={'cn': (287, 102, 392, 135)}, color={'cn': (43, 44, 43)}, button={'cn': (287, 102, 392, 135)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/OCR_BAR_AFFINITY.png'})
OCR_BAR_AFFINITY_LEVEL = Button(area={'cn': (161, 118, 180, 140)}, color={'cn': (92, 86, 63)}, button={'cn': (161, 118, 180, 140)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/OCR_BAR_AFFINITY_LEVEL.png'})
OCR_BAR_ARMS_NAME = Button(area={'cn': (93, 436, 457, 499)}, color={'cn': (91, 48, 35)}, button={'cn': (93, 436, 457, 499)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/OCR_BAR_ARMS_NAME.png'})
