from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BAR_ARMS_FILTER = Button(area={'cn': (544, 35, 570, 54)}, color={'cn': (77, 60, 14)}, button={'cn': (544, 35, 570, 54)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_ARMS_FILTER.png'})
BAR_FILTER_CLICK_SAFE_AREA = Button(area={'cn': (183, 24, 514, 139)}, color={'cn': (53, 55, 55)}, button={'cn': (183, 24, 514, 139)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_FILTER_CLICK_SAFE_AREA.png'})
BAR_FIRST_GITF = Button(area={'cn': (99, 578, 190, 671)}, color={'cn': (85, 70, 31)}, button={'cn': (99, 578, 190, 671)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_FIRST_GITF.png'})
BAR_GIFTS_GIVE = Button(area={'cn': (1103, 487, 1154, 513)}, color={'cn': (176, 125, 146)}, button={'cn': (1088, 440, 1166, 520)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_GIFTS_GIVE.png'})
BAR_GIFT_CHECK = Button(area={'cn': (1180, 600, 1241, 657)}, color={'cn': (87, 77, 52)}, button={'cn': (1180, 600, 1241, 657)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_GIFT_CHECK.png'})
BAR_GIFT_CHECK_2 = Button(area={'cn': (1064, 599, 1125, 656)}, color={'cn': (109, 82, 61)}, button={'cn': (1064, 599, 1125, 656)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_GIFT_CHECK_2.png'})
BAR_MENU = Button(area={'cn': (333, 225, 367, 257)}, color={'cn': (211, 56, 144)}, button={'cn': (269, 156, 814, 296)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/BAR_MENU.png'})
GIFT_SELECT_CHECK = Button(area={'cn': (1202, 619, 1212, 636)}, color={'cn': (91, 95, 97)}, button={'cn': (1202, 619, 1212, 636)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/GIFT_SELECT_CHECK.png'})
OCR_BAR_FIRST_GITF = Button(area={'cn': (128, 646, 195, 669)}, color={'cn': (119, 98, 53)}, button={'cn': (128, 646, 195, 669)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/bar/OCR_BAR_FIRST_GITF.png'})
