# --------------------
# Define non-modifiable values
# --------------------

# ==================== Aaa ====================

Restart:
  Scheduler:
    Enable:
      type: state
      value: true
      option: [ true, ]
      option_bold: [ true, ]
    # SuccessInterval: 0
    # FailureInterval: 0
    # ServerUpdate: 00:00

AaaReward:
  Scheduler:
    Enable:
      type: state
      value: true
      option: [ true, ]
      option_bold: [ true, ]