from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BACK_ARROW = Button(area={'cn': (46, 34, 74, 49)}, color={'cn': (107, 106, 107)}, button={'cn': (46, 34, 74, 49)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/ui/BACK_ARROW.png'})
DAILY_CHECK = Button(area={'cn': (203, 118, 302, 219)}, color={'cn': (116, 135, 135)}, button={'cn': (203, 118, 302, 219)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/ui/DAILY_CHECK.png'})
GOTO_MAIN = Button(area={'cn': (1215, 39, 1237, 59)}, color={'cn': (123, 123, 123)}, button={'cn': (1215, 39, 1237, 59)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/ui/GOTO_MAIN.png'})
MAIN_GOTO_CAMPAIGN = Button(area={'cn': (931, 316, 1121, 359)}, color={'cn': (174, 175, 178)}, button={'cn': (931, 316, 1121, 359)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/ui/MAIN_GOTO_CAMPAIGN.png'})
TRAINING_DAILY = Button(area={'cn': (382, 595, 472, 678)}, color={'cn': (69, 65, 64)}, button={'cn': (382, 595, 472, 678)}, file={'cn': './submodule/AlasAaaBridge/assets/cn/ui/TRAINING_DAILY.png'})
